### ISSUE TITLE
error message on start HA

### ISSUE THREAD

**Issue by ha4711** [thijsvanloef/palworld-server-docker#292]
## Describe the bug

on every start HA get this error, what is the reason?

## LOG
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:507
Integration: Sensor (documentation, issues)
First occurred: 18:21:36 (1 occurrences)
Last logged: 18:21:36

Error adding entities for domain sensor with platform synology_dsm
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 616, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 519, in async_get_or_create
    configuration_url = _validate_configuration_url(configuration_url)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 224, in _validate_configuration_url
    raise ValueError(f"invalid configuration_url '{value}'")
ValueError: invalid configuration_url 'http:////192.168.178.92:5000'

## OS information
Core 2024.1.6
Supervisor 2023.12.1
Operating System 11.5
Frontend 20240104.0

## Hardware information
intel-nuc
Generic x86-64
- CPU:  quad core Intel
- Memory:  4GB

## integration options:
new entities = off
activate update = off

**Comment by ha4711** [comment]
sorry wrong project
